### ISSUE TITLE
Warning in gradle 5.4.1

### ISSUE THREAD

**Issue by extmkv** [jansauer/gradle-poeditor-plugin#9]
I'm testing the puglin in gradle 5.4.1 and I can pull and push but the IDE(Android Studio) are showing the follows warnings:

- Access to `apiKeys` exceeds its access rights.
- Access to `projectId` exceeds its access rights.

**Gradle Version:** 5.4.1
**Plugib Version:** 1.0.0

**Comment by jansauer** [comment]
@extmkv can you check if https://stackoverflow.com/a/52677060 helps? So far i'm unable to reproduce this with my groovy/idea setup and based on the stackoverflow answer it sounds more like a warning about the gradle.build file then the plugin itself.

**Comment by extmkv** [comment]
@jansauer I've tried to move the following code from the project `build.gradle` to the app `build.gradle` and the warning just disappeared.

```groovy
poeditor {
        apiKey = POEDITOR_KEY
        projectId = POEDITOR_ID
}
```
